// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS6S9ZchREtwaYvqlgBMGwUzcyPnYufRw',
    appId: '1:980371250920:web:71e6a9257d43aca109f35d',
    messagingSenderId: '980371250920',
    projectId: 'trellis-lms',
    authDomain: 'trellis-lms.firebaseapp.com',
    databaseURL: 'https://trellis-lms-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trellis-lms.firebasestorage.app',
    measurementId: 'G-BB9L3QBCFE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbQpeMv8d_PJqvt8Snp-x1daYU_0Qqm9M',
    appId: '1:980371250920:android:bbbf0351d917970c09f35d',
    messagingSenderId: '980371250920',
    projectId: 'trellis-lms',
    databaseURL: 'https://trellis-lms-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trellis-lms.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX2j97JQ68OEYMqCgGM7RLxVOZkaf2o94',
    appId: '1:980371250920:ios:db74903a3cdc234609f35d',
    messagingSenderId: '980371250920',
    projectId: 'trellis-lms',
    databaseURL: 'https://trellis-lms-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trellis-lms.firebasestorage.app',
    iosBundleId: 'com.example.lms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX2j97JQ68OEYMqCgGM7RLxVOZkaf2o94',
    appId: '1:980371250920:ios:db74903a3cdc234609f35d',
    messagingSenderId: '980371250920',
    projectId: 'trellis-lms',
    databaseURL: 'https://trellis-lms-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trellis-lms.firebasestorage.app',
    iosBundleId: 'com.example.lms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAS6S9ZchREtwaYvqlgBMGwUzcyPnYufRw',
    appId: '1:980371250920:web:b93900a26a08057e09f35d',
    messagingSenderId: '980371250920',
    projectId: 'trellis-lms',
    authDomain: 'trellis-lms.firebaseapp.com',
    databaseURL: 'https://trellis-lms-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trellis-lms.firebasestorage.app',
    measurementId: 'G-EPDZNESLG1',
  );
}
